CREATE DATABASE TECHNICAL_CODING_ASSESMENT;
USE  TECHNICAL_CODING_ASSESMENT;
CREATE TABLE IF NOT EXISTS countries (
COUNTRY_ID varchar (2) ,
COUNTRY_NAME varchar(40) 
CHECK (COUNTRY_NAME IN ("Italy","India","China")) ,
REGION_ID decimal(10,0)  );
SHOW COLUMNS FROM COUNTRIES;
select * from countries;
